# IBM Content Manager Server Configuration
# Format: [SERVERNAME] followed by properties

ICMSERVER=LSDB
ICMSERVERREPTYPE=DB2
ICMSCHEMA=icmadmin
ICMDBAUTH=SERVER
ICMREMOTE=TRUE
ICMHOSTNAME=archndst.aokndsint.aok
ICMPORT=50000
ICMREMOTEDB=LSDB
ICMNODENAME=
ICMOSTYPE=LINUX
ICMJDBCDRIVER=com.ibm.db2.jcc.DB2Driver
ICMSSO=FALSE

ICMSERVER=AOKHB-ITU
ICMSERVERREPTYPE=ORACLE
ICMDBAUTH=SERVER
ICMSSO=FALSE
ICMSCHEMA=ICMADMIN
ICMREMOTE=TRUE
ICMHOSTNAME=narcht.oracle.aokndsint.aok
ICMPORT=1630
ICMREMOTEDB=narcht
ICMNODENAME=
ICMOSTYPE=
ICMJDBCDRIVER=oracle.jdbc.OracleDriver
ICMJDBCURL=jdbc:oracle:thin:@//narcht.oracle.aokndsint.aok:1630/narcht

# ICMSERVER=LSDB
# ICMSERVERREPTYPE=DB2
# ICMSCHEMA=icmadmin
# ICMDBAUTH=SERVER
# ICMREMOTE=TRUE
# ICMHOSTNAME=archndst.aokndsint.aok
# ICMPORT=50000
# ICMREMOTEDB=LSDB
# ICMNODENAME=
# ICMOSTYPE=LINUX
# ICMJDBCDRIVER=com.ibm.db2.jcc.DB2Driver
# ICMUSER=API_USER
# ICMSSO=FALSE
# 
# ICMSERVER=AOKHB-ITU
# ICMSERVERREPTYPE=ORACLE
# ICMSCHEMA=icmadmin
# ICMDBAUTH=SERVER
# ICMREMOTE=TRUE
# ICMHOSTNAME=narcht.oracle.aokndsint.aok
# ICMPORT=1630
# ICMREMOTEDB=narcht
# ICMNODENAME=
# ICMOSTYPE=
# ICMJDBCDRIVER=oracle.jdbc.OracleDriver
# ICMUSER=icmadmin
# ICMJDBCURL=jdbc:oracle:thin:@//narcht.oracle.aokndsint.aok:1630/narcht
# ICMSSO=FALSE

# ICMSERVER=LSDB
# ICMSERVERREPTYPE=DB2
# ICMSCHEMA=icmadmin
# ICMDBAUTH=SERVER
# ICMREMOTE=TRUE
# ICMHOSTNAME=archndst.aokndsint.aok
# ICMPORT=50000
# ICMREMOTEDB=LSDB
# ICMNODENAME=
# ICMOSTYPE=LINUX
# ICMJDBCDRIVER=com.ibm.db2.jcc.DB2Driver
# ICMSSO=FALSE
# 
# ICMSERVER=AOKHB-ITU
# ICMSERVERREPTYPE=ORACLE
# ICMDBAUTH=SERVER
# ICMSSO=FALSE
# ICMSCHEMA=icmadmin
# ICMREMOTE=TRUE
# ICMHOSTNAME=narcht.oracle.aokndsint.aok
# ICMPORT=1630
# ICMREMOTEDB=narcht
# ICMNODENAME=
# ICMOSTYPE=
# ICMJDBCDRIVER=oracle.jdbc.OracleDriver
# ICMJDBCURL=jdbc:oracle:thin:@//narcht.oracle.aokndsint.aok:1630/narcht
